
-- USERS TABLE

CREATE TABLE USERS(
	UserId INT IDENTITY(1,1) PRIMARY KEY,
	FullName VARCHAR(50) NOT NULL,
	Email varchar(20) UNIQUE NOT NULL,
	PhoneNumber varchar(20) UNIQUE,
	CreatedAt DATETIME DEFAULT GETDATE()

);

-- VENDORS TABLE

CREATE TABLE VENDORS(
	VendorId INT IDENTITY(1,1) PRIMARY KEY,
	VendorName VARCHAR(50) NOT NULL,
	Email VARCHAR(20) UNIQUE,
	CreatedAt DATETIME DEFAULT GETDATE()
);


-- ADDRESS TABLE

CREATE TABLE ADDRESSES(
	
		AddressId INT IDENTITY(1,1) PRIMARY KEY,
		UserId INT FOREIGN KEY REFERENCES USERS(UserId),
		AddressLine VARCHAR(100),
		City VARCHAR(20),
		State VARCHAR(30),
		Pincode varchar(20),
		CreateAt DATETIME DEFAULT GETDATE()

);


-- PRODUCT CATEGORIES TABLE

CREATE TABLE PRODUCTCATEGORIES(
	
	CategoryId INT IDENTITY(1,1) PRIMARY KEY,
	CategoryName VARCHAR(50) NOT NULL
);


-- PRODUCTS TABLE

CREATE TABLE PRODUCTS(

	ProductId INT IDENTITY(1,1) PRIMARY KEY,
	CategoryID INT FOREIGN KEY REFERENCES PRODUCTCATEGORIES(CategoryId),
	ProductName VARCHAR(30) NOT NULL,
	Description VARCHAR(100),
	ProductPrice DECIMAL(10,2),
	CreatedAt DATETIME DEFAULT GETDATE()
);


--INVENTORY TABLE

CREATE TABLE INVENTORY(
	
	InventryId INT IDENTITY(1,1) PRIMARY KEY,
	VendorId INT FOREIGN KEY REFERENCES VENDORS(VendorId),
	ProductId INT FOREIGN KEY REFERENCES PRODUCTS(ProductId),
	AvailableQuantity INT,
	LastUpdatedAt DATE DEFAULT GETDATE()
);


-- ORDERS TABLE

CREATE TABLE ORDERS(
	OrderId INT IDENTITY(1,1) PRIMARY KEY,
	UserId INT FOREIGN KEY REFERENCES USERS(UserId),
	VendorId INT FOREIGN KEY REFERENCES VENDORS(VendorId),
	OrderDate DATETIME DEFAULT GETDATE(),
	TotalAmount DECIMAL(10,2)
);


-- ORDER ITEMS TABLE

CREATE TABLE ORDERITEMS(

	OrderItemId INT IDENTITY(1,1) PRIMARY KEY,
	OrderId INT FOREIGN KEY REFERENCES ORDERS(OrderId),
	ProductId INT FOREIGN KEY REFERENCES PRODUCTS(ProductId),
	OrderQuentity INT,
	Price DECIMAL(10,2)
);


-- PAYMENTS TABLE

CREATE TABLE PAYMENTS(
	PaymentId INT IDENTITY(1,1) PRIMARY KEY,
	OrderId INT FOREIGN KEY REFERENCES ORDERS(OrderId),
	PaymentMode VARCHAR(30),
	PaymentStatus VARCHAR(30),
	PaidAt DATE DEFAULT GETDATE()
);



-- DELIVERY PARTNERS

CREATE TABLE DELIVERYPARTNERS(
	PartnerId INT IDENTITY(1,1) PRIMARY KEY,
	PartnerName VARCHAR(30),
	PhoneNumber VARCHAR(20)
);


-- STATUS TABLE

CREATE TABLE STATUS(

	StatusId INT IDENTITY(1,1) PRIMARY KEY,
	StatusName VARCHAR(30)
);


-- DELIVERY STATUS TABLE

CREATE TABLE DELIVERYSTATUS(
	DeliveryId INT IDENTITY(1,1) PRIMARY KEY,
	OrderId INT FOREIGN KEY REFERENCES ORDERS(OrderId),
	StatusId INT FOREIGN KEY REFERENCES STATUS(StatusId),
	UpdatedAt DATETIME DEFAULT GETDATE()
);


-- REVIEWS TABLE

CREATE TABLE REVIEWS(
	ReviewId INT IDENTITY(1,1) PRIMARY KEY,
	UserId INT FOREIGN KEY REFERENCES USERS(UserId),
	PrductId INT FOREIGN KEY REFERENCES PRODUCTS(ProductId),
	Rating Int CHECK(Rating BETWEEN 1 AND 5),
	Comments VARCHAR(50),
	CreatedAt DATETIME DEFAULT GETDATE()
);

