-- 1. Get All Orders by a User (Customer or Vendor)
-- 2. Order Summary with Items (Orders, OrderItems, Products)
-- 3. Total Revenue Generated by Each Vendor
-- 4. Top 5 Bestselling Products
-- 5. Average Product Rating
-- 6. Delivery Status of a Particular Order
-- 7. Daily Order Count
-- 8. Top Customers by Order Value
-- 9. Low Stock Products Per Vendor
-- 10. Search Products by Keyword (Flexible Query)



-- 1. Get All Orders by a User (Customer or Vendor)

-- By The Customer
SELECT ORDERS.OrderId,ORDERS.OrderDate,ORDERS.TotalAmount,USERS.UserId,USERS.FullName FROM 
ORDERS JOIN USERS ON USERS.UserId = ORDERS.UserId where USERS.UserId = 2;

-- By The Vendors
SELECT ORDERS.OrderId, ORDERS.OrderDate,ORDERS.TotalAmount,VENDORS.VendorId,VENDORS.VendorName
FROM ORDERS JOIN VENDORS ON ORDERS.VendorId = VENDORS.VendorId WHERE VENDORS.VendorId = 2;


-- 2. Order Summary with Items (Orders, OrderItems, Products)

SELECT ORDERS.OrderId,ORDERS.OrderDate,ORDERITEMS.OrderQuentity,PRODUCTS.ProductName,PRODUCTS.ProductPrice
FROM ORDERS JOIN ORDERITEMS ON ORDERS.OrderId = ORDERITEMS.OrderId
JOIN PRODUCTS ON PRODUCTS.ProductId = ORDERITEMS.ProductId;


-- 3. Total Revenue Generated by Each Vendor

SELECT VENDORS.VendorId, VENDORS.VendorName, SUM(ORDERS.TotalAmount) AS TotalRevenue
FROM VENDORS JOIN ORDERS ON ORDERS.VendorId = VENDORS.VendorId
GROUP BY VENDORS.VendorId,VENDORS.VendorName;


-- 4. Top 5 Bestselling Products

with CTE as (select PRODUCTS.ProductId,PRODUCTS.ProductName, SUM(ORDERITEMS.OrderQuentity) as Total_Amount
from PRODUCTS join ORDERITEMS on PRODUCTS.ProductId = ORDERITEMS.ProductId 
join ORDERS on ORDERS.OrderId = ORDERITEMS.OrderId 
group by PRODUCTS.ProductId,PRODUCTS.ProductName)

select Top 5 ProductId,ProductName,Total_Amount from CTE order by Total_Amount desc;


-- 5. Average Product Rating

SELECT PRODUCTS.ProductId,PRODUCTS.ProductName,AVG(Reviews.Rating) AS Rating_Average
FROM Reviews JOIN PRODUCTS ON PRODUCTS.ProductId = Reviews.ProductID
GROUP BY PRODUCTS.ProductId,PRODUCTS.ProductName ORDER BY AVG(Reviews.Rating) DESC;

-- 6. Delivery Status of a Particular Order

SELECT ORDERS.OrderId,DELIVERYSTATUS.StatusId, STATUS.StatusName,DELIVERYSTATUS.UpdatedAt
FROM ORDERS JOIN DELIVERYSTATUS ON ORDERS.OrderId = DELIVERYSTATUS.OrderId
JOIN STATUS ON STATUS.StatusId = DELIVERYSTATUS.StatusId WHERE ORDERS.OrderId = 4;


-- 8. Top Customers by Order Value

SELECT Top 1 USERS.UserId,USERS.FullName,SUM(ORDERS.TotalAmount) AS Total_Value
FROM USERS JOIN ORDERS ON ORDERS.UserId = USERS.UserId
group by  USERS.UserId,USERS.FullName order by SUM(ORDERS.TotalAmount) desc;

-- 7. Daily Order Count

select OrderDate,count(OrderId) as OrderCount from ORDERS GROUP BY OrderDate ORDER BY OrderDate;

-- 9. Low Stock Products Per Vendor

SELECT DISTINCT VENDORS.VendorName,PRODUCTS.ProductName,INVENTORY.AvailableQuantity 
FROM VENDORS JOIN ORDERS ON ORDERS.VendorId = VENDORS.VendorId
JOIN INVENTORY ON INVENTORY.VendorId = VENDORS.VendorId
JOIN PRODUCTS on PRODUCTS.ProductId = INVENTORY.ProductId
ORDER BY INVENTORY.AvailableQuantity;


-- 10. Search Products by Keyword (Flexible Query)'

SELECT * FROM PRODUCTS WHERE ProductName LIKE '%_2_%';


